name: Build, Push and Deploy Docker Images - CNAPP demo (BP)

on: push

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the entire repo history is checked out

      - name: Update Kubernetes manifests
        run: |
          sed -i "s|tyrion75/westeros:v1\${COMMIT_COUNT}-|${{ secrets.DOCKERHUB_USERNAME }}/westeros:v1$(git rev-list --count HEAD)-|g" release/kubernetes-manifests.yaml

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install or update AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set AWS security token and principal ARN
        run: |
          export AWS_SECURITY_TOKEN=${{ secrets.AWS_SECURITY_TOKEN }}
          export X_PRINCIPAL_ARN=${{ secrets.X_PRINCIPAL_ARN }}

      - name: Verify AWS and EKS access
        run: |
          aws sts get-caller-identity
          aws eks list-clusters --region ${{ secrets.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name BP-test
          kubectl config view --raw > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Verify cluster access
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Verify EKS Permissions
        run: |
          kubectl get pods --all-namespaces
          kubectl get services --all-namespaces
          kubectl describe namespace kube-system
          kubectl run test-pod --image=nginx --restart=Never
          kubectl delete pod test-pod

      - name: Apply updated Kubernetes manifests in EKS
        run: |
          kubectl apply -f release/kubernetes-manifests.yaml --validate=false

      - name: Commit and push updates to YAML files
        run: |
          git config --global user.email "binhphan@me.com"
          git config --global user.name "bphansg"
          git add release/kubernetes-manifests.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Docker image references in YAML files" && git push)
