name: Build, Push and Deploy Docker Images - CNAPP demo

on: push

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Ensures the entire repo history is checked out

      - name: Set up Docker Builder
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: tyrion
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image for each service
        id: build_and_push
        run: |
          mkdir -p microservices-demo-eks-project/kubernetes-manifests
          
          # Loop through each service directory
          for dir in src/*/; do
            if [ -f "$dir/Dockerfile" ]; then
              service_name=$(basename "$dir")
              echo "Building Docker image for $service_name"
              
              # Define the image tag
              image_tag="v1$(git rev-list --count HEAD)-$service_name"
              
              # Build the Docker image
              echo "Building Docker image with tag $image_tag"
              docker build -t tyrion75/westeros:$image_tag "$dir"
              
              # Push the Docker image
              echo "Pushing Docker image to registry"
              docker push tyrion75/westeros:$image_tag
              
              # Update image references in YAML files
              find "microservices-demo-eks-project/kubernetes-manifests" -type f -name '*.yaml' -exec sed -i "s|tyrion75/westeros:[^ ]*|tyrion75/westeros:${image_tag}|g" {} +
            fi
          done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure Kubernetes
        run: |
          aws eks update-kubeconfig --name BP-test --region us-west-2

      - name: Apply updated Kubernetes manifests in EKS
        run: |
          kubectl apply -f "microservices-demo-eks-project/kubernetes-manifests" --recursive --validate=false

      - name: Commit and push updates to YAML files
        run: |
          git config --global user.email "binhphan@me.com"
          git config --global user.name "bphansg"
          git add "microservices-demo-eks-project/kubernetes-manifests"
          git commit -m "Update Docker image references in YAML files"
          git push origin main
