name: Build, Push and Deploy Docker Images - CNAPP demo (BP)

on: push

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the entire repo history is checked out

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for changed services
        run: |
          # Get the list of changed files
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          
          # Loop through each service directory
          for dir in src/*/; do
            if [ -f "$dir/Dockerfile" ]; then
              service_name=$(basename "$dir")
              
              # Check if any files in this service directory have changed or if the image doesn't exist
              if echo "$CHANGED_FILES" | grep -q "$dir" || ! docker pull ${{ secrets.DOCKERHUB_USERNAME }}/$service_name:latest &> /dev/null; then
                echo "Changes detected or image not found for $service_name. Building and pushing Docker image."
                
                # Build the Docker image
                docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/$service_name:latest "$dir"
                
                # Push the Docker image
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/$service_name:latest
                
                # Update image references in YAML files
                sed -i "s|image: .*$service_name.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/$service_name:latest|g" release/kubernetes-manifests.yaml
              else
                echo "No changes detected and image exists for $service_name. Skipping build and push."
              fi
            fi
          done

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name BP-test --region ${{ secrets.AWS_REGION }}

      - name: Apply updated Kubernetes manifests in EKS
        run: |
          kubectl apply -f release/kubernetes-manifests.yaml --validate=false

      - name: Commit and push updates to YAML files
        run: |
          git config --global user.email "binhphan@me.com"
          git config --global user.name "bphansg"
          git add release/kubernetes-manifests.yaml
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update Docker image references in YAML files" && git push)
